### ISSUE TITLE
Remove translation related code

### ISSUE THREAD

**Issue by alexandermendes** [alexandermendes/BL-pybossa-theme#20]
It's not going to be possible to maintain translations for our additional content. So remove anything related to these.

**Comment by alexandermendes** [comment]
This should also remove errors such as this:

```
Exception on / [GET]
Traceback (most recent call last):
  File "/var/www/pybossa/env/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/var/www/pybossa/env/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/var/www/pybossa/env/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/var/www/pybossa/env/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/var/www/pybossa/env/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/www/pybossa/pybossa/view/home.py", line 64, in home
    return render_template('/home/index.html', **d)
  File "/var/www/pybossa/env/lib/python2.7/site-packages/flask/templating.py", line 128, in render_template
    context, ctx.app)
  File "/var/www/pybossa/env/lib/python2.7/site-packages/flask/templating.py", line 110, in _render
    rv = template.render(context)
  File "/var/www/pybossa/env/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/var/www/pybossa/env/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/var/www/pybossa/pybossa/themes/libcrowds-pybossa-theme/templates/home/index.html", line 3, in top-level template code
    {% import "account/_helpers.html" as account_helper %}
  File "/var/www/pybossa/pybossa/themes/libcrowds-pybossa-theme/templates/base.html", line 65, in top-level template code
    {% include "_navbar.html" %}
  File "/var/www/pybossa/pybossa/themes/libcrowds-pybossa-theme/templates/_navbar.html", line 21, in top-level template code
    <li class="nav-link {% if active_page == 'about' %} active{% endif %}"><a href="{{ url_for('home.about')}}">{{ _('About') }}</a></li>
  File "/var/www/pybossa/env/lib/python2.7/site-packages/jinja2/ext.py", line 132, in _gettext_alias
    return __context.call(__context.resolve('gettext'), *args, **kwargs)
  File "/var/www/pybossa/env/lib/python2.7/site-packages/jinja2/ext.py", line 138, in gettext
    rv = __context.call(func, __string)
  File "/var/www/pybossa/env/lib/python2.7/site-packages/flask_babel/__init__.py", line 116, in <lambda>
    lambda x: get_translations().ugettext(x),
  File "/var/www/pybossa/env/lib/python2.7/site-packages/flask_babel/__init__.py", line 196, in get_translations
    translations = support.Translations.load(dirname, [get_locale()])
  File "/var/www/pybossa/env/lib/python2.7/site-packages/flask_babel/__init__.py", line 219, in get_locale
    locale = Locale.parse(rv)
  File "/var/www/pybossa/env/lib/python2.7/site-packages/babel/core.py", line 313, in parse
    raise UnknownLocaleError(input_id)
UnknownLocaleError: unknown locale 'e'
```

**Comment by alexandermendes** [comment]
Done: https://github.com/LibCrowds/libcrowds-pybossa-theme/commit/e052b9d50ccf7202616c4bfbff27a0cc10e3e95e
